// <auto-generated />
using System;
using Himgiri.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Himgiri.Infrastructure.Migrations
{
    [DbContext(typeof(HimgiriDbContext))]
    [Migration("20260516102236_InitialSchoolPortalSetup")]
    partial class InitialSchoolPortalSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Himgiri.Core.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            CreatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6471),
                            Email = "superadmin@himgirigoods.com",
                            IsActive = true,
                            Name = "Super Admin",
                            PasswordHash = "$2a$11$rBV2JDeWW3.vKyeCtBiWMurq3vm5JJ1PsHpFN0nHT5hGDYSc3wGWe",
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6472)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            CreatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6476),
                            Email = "pradeep@himgirigoods.com",
                            IsActive = true,
                            Name = "Pradeep Jagadale",
                            PasswordHash = "$2a$11$rBV2JDeWW3.vKyeCtBiWMurq3vm5JJ1PsHpFN0nHT5hGDYSc3wGWe",
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6477)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            CreatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6480),
                            Email = "inventory@himgirigoods.com",
                            IsActive = true,
                            Name = "Inventory Manager",
                            PasswordHash = "$2a$11$rBV2JDeWW3.vKyeCtBiWMurq3vm5JJ1PsHpFN0nHT5hGDYSc3wGWe",
                            Role = 1,
                            UpdatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6481)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            CreatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6484),
                            Email = "orders1@himgirigoods.com",
                            IsActive = true,
                            Name = "Order Manager 1",
                            PasswordHash = "$2a$11$rBV2JDeWW3.vKyeCtBiWMurq3vm5JJ1PsHpFN0nHT5hGDYSc3wGWe",
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6485)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            CreatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6488),
                            Email = "orders2@himgirigoods.com",
                            IsActive = true,
                            Name = "Order Manager 2",
                            PasswordHash = "$2a$11$rBV2JDeWW3.vKyeCtBiWMurq3vm5JJ1PsHpFN0nHT5hGDYSc3wGWe",
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6488)
                        });
                });

            modelBuilder.Entity("Himgiri.Core.Entities.GstSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<decimal>("CgstPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GstPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("HsnCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("SgstPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GstSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Category = 0,
                            CgstPercent = 0m,
                            CreatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6764),
                            EffectiveFrom = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6738),
                            GstPercent = 0m,
                            HsnCode = "4901",
                            IsActive = true,
                            SgstPercent = 0m,
                            UpdatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6765)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Category = 3,
                            CgstPercent = 6m,
                            CreatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6772),
                            EffectiveFrom = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6766),
                            GstPercent = 12m,
                            HsnCode = "4820",
                            IsActive = true,
                            SgstPercent = 6m,
                            UpdatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6773)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Category = 1,
                            CgstPercent = 6m,
                            CreatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6777),
                            EffectiveFrom = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6773),
                            GstPercent = 12m,
                            HsnCode = "4820",
                            IsActive = true,
                            SgstPercent = 6m,
                            UpdatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6778)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            Category = 2,
                            CgstPercent = 9m,
                            CreatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6781),
                            EffectiveFrom = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6778),
                            GstPercent = 18m,
                            HsnCode = "4202",
                            IsActive = true,
                            SgstPercent = 9m,
                            UpdatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6782)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            Category = 4,
                            CgstPercent = 9m,
                            CreatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6785),
                            EffectiveFrom = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6782),
                            GstPercent = 18m,
                            HsnCode = "9965",
                            IsActive = true,
                            SgstPercent = 9m,
                            UpdatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6786)
                        });
                });

            modelBuilder.Entity("Himgiri.Core.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<decimal>("GstPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("HsnCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("StockQty")
                        .HasColumnType("integer");

                    b.Property<int>("StorageStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Grade");

                    b.HasIndex("IsActive");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            Category = 3,
                            CreatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6864),
                            Description = "DPS Hinjawadi School Almanac",
                            Grade = 2,
                            GstPercent = 12m,
                            HsnCode = "4820",
                            IsActive = true,
                            Name = "Almanac 2026-27",
                            Price = 150m,
                            StockQty = 200,
                            StorageStatus = 0,
                            UpdatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6864)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000002"),
                            Category = 1,
                            CreatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6869),
                            Description = "DPS Hinjawadi Portfolio File",
                            Grade = 2,
                            GstPercent = 12m,
                            HsnCode = "4820",
                            IsActive = true,
                            Name = "Portfolio File",
                            Price = 80m,
                            StockQty = 200,
                            StorageStatus = 0,
                            UpdatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6869)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000003"),
                            Category = 3,
                            CreatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6877),
                            Description = "DPS Public Speaking Journal",
                            Grade = 2,
                            GstPercent = 12m,
                            HsnCode = "4820",
                            IsActive = true,
                            Name = "Public Speaking Journal",
                            Price = 120m,
                            StockQty = 200,
                            StorageStatus = 0,
                            UpdatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6877)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000004"),
                            Category = 0,
                            CreatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6881),
                            Description = "Marathi Theme Book — delivered to classroom June 2026",
                            Grade = 2,
                            GstPercent = 0m,
                            HsnCode = "4901",
                            IsActive = true,
                            Name = "Majet Shikuya Marathi",
                            Price = 90m,
                            StockQty = 200,
                            StorageStatus = 1,
                            UpdatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6882)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000005"),
                            Category = 0,
                            CreatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6886),
                            Description = "Grade 2 Theme Book — delivered to classroom June 2026",
                            Grade = 2,
                            GstPercent = 0m,
                            HsnCode = "4901",
                            IsActive = true,
                            Name = "Theme Book Grade 2",
                            Price = 110m,
                            StockQty = 200,
                            StorageStatus = 1,
                            UpdatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6886)
                        });
                });

            modelBuilder.Entity("Himgiri.Core.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("DeliveryGst")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("boolean");

                    b.Property<string>("JodoPaymentId")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("RefundReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TotalGst")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("PaymentStatus");

                    b.HasIndex("Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cgst")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GstAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("GstPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("HsnCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Sgst")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierInvoiceNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.PurchaseOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderItems");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.StockLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("NewQty")
                        .HasColumnType("integer");

                    b.Property<int>("OldQty")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("StockLogs");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GstNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.VendorSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gstin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvoicePrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LastInvoiceNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VendorSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Address = "Hinjawadi, Pune, Maharashtra",
                            CompanyName = "Himgiri Goods Pvt. Ltd",
                            ContactEmail = "support@himgirigoods.com",
                            ContactPhone = "PENDING_FROM_CLIENT",
                            CreatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6820),
                            Gstin = "PENDING_FROM_CLIENT",
                            InvoicePrefix = "HG",
                            LastInvoiceNumber = 0,
                            UpdatedAt = new DateTime(2026, 5, 16, 10, 22, 34, 67, DateTimeKind.Utc).AddTicks(6821)
                        });
                });

            modelBuilder.Entity("Himgiri.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("Himgiri.Core.Entities.Item", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Himgiri.Core.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("Himgiri.Core.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.PurchaseOrderItem", b =>
                {
                    b.HasOne("Himgiri.Core.Entities.Item", "Item")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Himgiri.Core.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.StockLog", b =>
                {
                    b.HasOne("Himgiri.Core.Entities.Item", "Item")
                        .WithMany("StockLogs")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.Item", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("PurchaseOrderItems");

                    b.Navigation("StockLogs");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
