// <auto-generated />
using System;
using Himgiri.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Himgiri.Infrastructure.Migrations
{
    [DbContext(typeof(HimgiriDbContext))]
    [Migration("20260701184541_AddGstRateSeed")]
    partial class AddGstRateSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Himgiri.Core.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(3408),
                            Email = "superadmin@himgirigoods.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Super Admin",
                            PasswordHash = "$2a$11$rBV2JDeWW3.vKyeCtBiWMurq3vm5JJ1PsHpFN0nHT5hGDYSc3wGWe",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(3440),
                            Email = "pradeep@himgirigoods.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Pradeep Jagadale",
                            PasswordHash = "$2a$11$rBV2JDeWW3.vKyeCtBiWMurq3vm5JJ1PsHpFN0nHT5hGDYSc3wGWe",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(3447),
                            Email = "inventory@himgirigoods.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Inventory Manager",
                            PasswordHash = "$2a$11$rBV2JDeWW3.vKyeCtBiWMurq3vm5JJ1PsHpFN0nHT5hGDYSc3wGWe",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(3454),
                            Email = "orders1@himgirigoods.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Order Manager 1",
                            PasswordHash = "$2a$11$rBV2JDeWW3.vKyeCtBiWMurq3vm5JJ1PsHpFN0nHT5hGDYSc3wGWe",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(3459),
                            Email = "orders2@himgirigoods.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Order Manager 2",
                            PasswordHash = "$2a$11$rBV2JDeWW3.vKyeCtBiWMurq3vm5JJ1PsHpFN0nHT5hGDYSc3wGWe",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Himgiri.Core.Entities.ApiErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("QueryParams")
                        .HasColumnType("text");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<int>("ResponseCode")
                        .HasColumnType("integer");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ApiErrorLogs");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4351),
                            Description = "Primary Grade 1",
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Grade 1",
                            ShortName = "G1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4358),
                            Description = "Primary Grade 2",
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Grade 2",
                            ShortName = "G2"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4365),
                            Description = "Primary Grade 3",
                            DisplayOrder = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Grade 3",
                            ShortName = "G3"
                        });
                });

            modelBuilder.Entity("Himgiri.Core.Entities.GstRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cess")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Cgst")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HsnCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Igst")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Sgst")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GstRates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000001"),
                            Cess = 0m,
                            Cgst = 0m,
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4467),
                            Description = "School Textbooks Exempt from GST",
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HsnCode = "4901",
                            Igst = 0m,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Books Exempt",
                            Rate = 0m,
                            Sgst = 0m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000002"),
                            Cess = 0m,
                            Cgst = 6m,
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4487),
                            Description = "Notebooks and Stationery items under 12% GST",
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HsnCode = "4820",
                            Igst = 12m,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Stationery GST 12%",
                            Rate = 12m,
                            Sgst = 6m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000003"),
                            Cess = 0m,
                            Cgst = 9m,
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4495),
                            Description = "School Bags and Backpacks under 18% GST",
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HsnCode = "4202",
                            Igst = 18m,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bags GST 18%",
                            Rate = 18m,
                            Sgst = 9m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000004"),
                            Cess = 0m,
                            Cgst = 9m,
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4501),
                            Description = "Logistics and Shipping charges under 18% GST",
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HsnCode = "9965",
                            Igst = 18m,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Delivery Fee GST 18%",
                            Rate = 18m,
                            Sgst = 9m
                        });
                });

            modelBuilder.Entity("Himgiri.Core.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("GstRateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStockInitialized")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Mrp")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("StockQty")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int>("StorageStatus")
                        .HasColumnType("integer");

                    b.Property<int>("TargetQty")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pieces (Pcs)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GstRateId");

                    b.HasIndex("IsActive");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000011"),
                            CategoryId = new Guid("00000000-0000-0000-0006-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4819),
                            Description = "Interactive English Reader for Grade 1",
                            GstRateId = new Guid("00000000-0000-0000-0009-000000000001"),
                            ImageUrl = "https://picsum.photos/200/300?random=11",
                            IsActive = true,
                            IsDeleted = false,
                            IsStockInitialized = true,
                            Mrp = 180m,
                            Name = "Grade 1 English Textbook",
                            Price = 180m,
                            PurchasePrice = 120m,
                            StockQty = 150,
                            StorageStatus = 0,
                            TargetQty = 150,
                            Unit = "Pieces (Pcs)"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000012"),
                            CategoryId = new Guid("00000000-0000-0000-0006-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4831),
                            Description = "Ruled Journal for Grade 1 practice",
                            GstRateId = new Guid("00000000-0000-0000-0009-000000000002"),
                            ImageUrl = "https://picsum.photos/200/300?random=12",
                            IsActive = true,
                            IsDeleted = false,
                            IsStockInitialized = true,
                            Mrp = 45m,
                            Name = "Grade 1 Red Notebook",
                            Price = 40m,
                            PurchasePrice = 25m,
                            StockQty = 300,
                            StorageStatus = 0,
                            TargetQty = 300,
                            Unit = "Pieces (Pcs)"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000013"),
                            CategoryId = new Guid("00000000-0000-0000-0006-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4842),
                            Description = "Stationery box containing pencils, eraser, and ruler",
                            GstRateId = new Guid("00000000-0000-0000-0009-000000000002"),
                            ImageUrl = "https://picsum.photos/200/300?random=13",
                            IsActive = true,
                            IsDeleted = false,
                            IsStockInitialized = true,
                            Mrp = 80m,
                            Name = "Grade 1 Premium Pencil Box",
                            Price = 70m,
                            PurchasePrice = 45m,
                            StockQty = 200,
                            StorageStatus = 0,
                            TargetQty = 200,
                            Unit = "Pieces (Pcs)"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            CategoryId = new Guid("00000000-0000-0000-0006-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4854),
                            Description = "DPS Hinjawadi School Almanac",
                            GstRateId = new Guid("00000000-0000-0000-0009-000000000002"),
                            ImageUrl = "https://picsum.photos/200/300?random=1",
                            IsActive = true,
                            IsDeleted = false,
                            IsStockInitialized = true,
                            Mrp = 180m,
                            Name = "Almanac 2026-27",
                            Price = 150m,
                            PurchasePrice = 100m,
                            StockQty = 120,
                            StorageStatus = 0,
                            TargetQty = 150,
                            Unit = "Pieces (Pcs)"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000002"),
                            CategoryId = new Guid("00000000-0000-0000-0006-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4871),
                            Description = "DPS Hinjawadi Portfolio File",
                            GstRateId = new Guid("00000000-0000-0000-0009-000000000002"),
                            ImageUrl = "https://picsum.photos/200/300?random=2",
                            IsActive = true,
                            IsDeleted = false,
                            IsStockInitialized = true,
                            Mrp = 90m,
                            Name = "Portfolio File",
                            Price = 80m,
                            PurchasePrice = 50m,
                            StockQty = 250,
                            StorageStatus = 0,
                            TargetQty = 300,
                            Unit = "Pieces (Pcs)"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000003"),
                            CategoryId = new Guid("00000000-0000-0000-0006-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4883),
                            Description = "DPS Public Speaking Journal",
                            GstRateId = new Guid("00000000-0000-0000-0009-000000000002"),
                            ImageUrl = "https://picsum.photos/200/300?random=3",
                            IsActive = true,
                            IsDeleted = false,
                            IsStockInitialized = true,
                            Mrp = 140m,
                            Name = "Public Speaking Journal",
                            Price = 120m,
                            PurchasePrice = 80m,
                            StockQty = 180,
                            StorageStatus = 0,
                            TargetQty = 200,
                            Unit = "Pieces (Pcs)"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000004"),
                            CategoryId = new Guid("00000000-0000-0000-0006-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4892),
                            Description = "Marathi Theme Book",
                            GstRateId = new Guid("00000000-0000-0000-0009-000000000001"),
                            ImageUrl = "https://picsum.photos/200/300?random=4",
                            IsActive = true,
                            IsDeleted = false,
                            IsStockInitialized = true,
                            Mrp = 100m,
                            Name = "Majet Shikuya Marathi",
                            Price = 90m,
                            PurchasePrice = 60m,
                            StockQty = 90,
                            StorageStatus = 0,
                            TargetQty = 100,
                            Unit = "Pieces (Pcs)"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000005"),
                            CategoryId = new Guid("00000000-0000-0000-0006-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4903),
                            Description = "Grade 2 Theme Book",
                            GstRateId = new Guid("00000000-0000-0000-0009-000000000001"),
                            ImageUrl = "https://picsum.photos/200/300?random=5",
                            IsActive = true,
                            IsDeleted = false,
                            IsStockInitialized = true,
                            Mrp = 130m,
                            Name = "Theme Book Grade 2",
                            Price = 110m,
                            PurchasePrice = 75m,
                            StockQty = 0,
                            StorageStatus = 1,
                            TargetQty = 150,
                            Unit = "Pieces (Pcs)"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000031"),
                            CategoryId = new Guid("00000000-0000-0000-0006-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4913),
                            Description = "Mathematics textbook for Grade 3",
                            GstRateId = new Guid("00000000-0000-0000-0009-000000000001"),
                            ImageUrl = "https://picsum.photos/200/300?random=31",
                            IsActive = true,
                            IsDeleted = false,
                            IsStockInitialized = true,
                            Mrp = 220m,
                            Name = "Grade 3 Math Magic",
                            Price = 220m,
                            PurchasePrice = 150m,
                            StockQty = 140,
                            StorageStatus = 0,
                            TargetQty = 150,
                            Unit = "Pieces (Pcs)"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000032"),
                            CategoryId = new Guid("00000000-0000-0000-0006-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4924),
                            Description = "Science and environment textbook for Grade 3",
                            GstRateId = new Guid("00000000-0000-0000-0009-000000000001"),
                            ImageUrl = "https://picsum.photos/200/300?random=32",
                            IsActive = true,
                            IsDeleted = false,
                            IsStockInitialized = true,
                            Mrp = 240m,
                            Name = "Grade 3 Science Explorer",
                            Price = 240m,
                            PurchasePrice = 160m,
                            StockQty = 130,
                            StorageStatus = 0,
                            TargetQty = 150,
                            Unit = "Pieces (Pcs)"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000033"),
                            CategoryId = new Guid("00000000-0000-0000-0006-000000000004"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4933),
                            Description = "Heavy duty school backpack for Grade 3",
                            GstRateId = new Guid("00000000-0000-0000-0009-000000000003"),
                            ImageUrl = "https://picsum.photos/200/300?random=33",
                            IsActive = true,
                            IsDeleted = false,
                            IsStockInitialized = true,
                            Mrp = 750m,
                            Name = "Grade 3 School Bag",
                            Price = 650m,
                            PurchasePrice = 450m,
                            StockQty = 80,
                            StorageStatus = 0,
                            TargetQty = 100,
                            Unit = "Pieces (Pcs)"
                        });
                });

            modelBuilder.Entity("Himgiri.Core.Entities.ItemCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CgstPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultGstRateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("GstPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("HsnCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("SgstPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DefaultGstRateId");

                    b.ToTable("ItemCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000001"),
                            CgstPercent = 0m,
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4627),
                            DefaultGstRateId = new Guid("00000000-0000-0000-0009-000000000001"),
                            Description = "School Textbooks",
                            DisplayOrder = 1,
                            GstPercent = 0m,
                            HsnCode = "4901",
                            IsActive = true,
                            IsDeleted = false,
                            IsTaxable = false,
                            Name = "Textbook",
                            SgstPercent = 0m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000002"),
                            CgstPercent = 6m,
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4636),
                            DefaultGstRateId = new Guid("00000000-0000-0000-0009-000000000002"),
                            Description = "School Stationery",
                            DisplayOrder = 2,
                            GstPercent = 12m,
                            HsnCode = "4820",
                            IsActive = true,
                            IsDeleted = false,
                            IsTaxable = true,
                            Name = "Stationery",
                            SgstPercent = 6m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000003"),
                            CgstPercent = 6m,
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4639),
                            DefaultGstRateId = new Guid("00000000-0000-0000-0009-000000000002"),
                            Description = "School Journals",
                            DisplayOrder = 3,
                            GstPercent = 12m,
                            HsnCode = "4820",
                            IsActive = true,
                            IsDeleted = false,
                            IsTaxable = true,
                            Name = "Journal",
                            SgstPercent = 6m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000004"),
                            CgstPercent = 9m,
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4642),
                            DefaultGstRateId = new Guid("00000000-0000-0000-0009-000000000003"),
                            Description = "School Bags",
                            DisplayOrder = 4,
                            GstPercent = 18m,
                            HsnCode = "4202",
                            IsActive = true,
                            IsDeleted = false,
                            IsTaxable = true,
                            Name = "Bag",
                            SgstPercent = 9m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000005"),
                            CgstPercent = 9m,
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4645),
                            DefaultGstRateId = new Guid("00000000-0000-0000-0009-000000000004"),
                            Description = "Delivery Charges",
                            DisplayOrder = 5,
                            GstPercent = 18m,
                            HsnCode = "9965",
                            IsActive = true,
                            IsDeleted = false,
                            IsTaxable = true,
                            Name = "Delivery Fee",
                            SgstPercent = 9m
                        });
                });

            modelBuilder.Entity("Himgiri.Core.Entities.ItemGrade", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.HasKey("ItemId", "GradeId");

                    b.HasIndex("GradeId");

                    b.ToTable("ItemGrades");

                    b.HasData(
                        new
                        {
                            ItemId = new Guid("00000000-0000-0000-0004-000000000011"),
                            GradeId = new Guid("00000000-0000-0000-0005-000000000001")
                        },
                        new
                        {
                            ItemId = new Guid("00000000-0000-0000-0004-000000000012"),
                            GradeId = new Guid("00000000-0000-0000-0005-000000000001")
                        },
                        new
                        {
                            ItemId = new Guid("00000000-0000-0000-0004-000000000013"),
                            GradeId = new Guid("00000000-0000-0000-0005-000000000001")
                        },
                        new
                        {
                            ItemId = new Guid("00000000-0000-0000-0004-000000000001"),
                            GradeId = new Guid("00000000-0000-0000-0005-000000000002")
                        },
                        new
                        {
                            ItemId = new Guid("00000000-0000-0000-0004-000000000002"),
                            GradeId = new Guid("00000000-0000-0000-0005-000000000002")
                        },
                        new
                        {
                            ItemId = new Guid("00000000-0000-0000-0004-000000000003"),
                            GradeId = new Guid("00000000-0000-0000-0005-000000000002")
                        },
                        new
                        {
                            ItemId = new Guid("00000000-0000-0000-0004-000000000004"),
                            GradeId = new Guid("00000000-0000-0000-0005-000000000002")
                        },
                        new
                        {
                            ItemId = new Guid("00000000-0000-0000-0004-000000000005"),
                            GradeId = new Guid("00000000-0000-0000-0005-000000000002")
                        },
                        new
                        {
                            ItemId = new Guid("00000000-0000-0000-0004-000000000031"),
                            GradeId = new Guid("00000000-0000-0000-0005-000000000003")
                        },
                        new
                        {
                            ItemId = new Guid("00000000-0000-0000-0004-000000000032"),
                            GradeId = new Guid("00000000-0000-0000-0005-000000000003")
                        },
                        new
                        {
                            ItemId = new Guid("00000000-0000-0000-0004-000000000033"),
                            GradeId = new Guid("00000000-0000-0000-0005-000000000003")
                        });
                });

            modelBuilder.Entity("Himgiri.Core.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("DeliveryGst")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("boolean");

                    b.Property<string>("JodoPaymentId")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("RefundReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TotalGst")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GradeId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("PaymentStatus");

                    b.HasIndex("Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cgst")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("GstAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("GstPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("HsnCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Sgst")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusHistories");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.PriceAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("NewMrp")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("NewPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("OldMrp")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("OldPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("PriceAuditLogs");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierInvoiceNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.PurchaseOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderItems");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.SchoolKit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GradeId", "IsActive")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true AND \"IsDeleted\" = false");

                    b.ToTable("SchoolKits");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(5263),
                            Description = "Essential textbooks and stationery bundle for Grade 1",
                            GradeId = new Guid("00000000-0000-0000-0005-000000000001"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Grade 1 Standard Kit"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(5274),
                            Description = "Complete academic package including textbooks and journals for Grade 2",
                            GradeId = new Guid("00000000-0000-0000-0005-000000000002"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Grade 2 Premium Kit"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(5279),
                            Description = "All required textbooks and school bag for Grade 3",
                            GradeId = new Guid("00000000-0000-0000-0005-000000000003"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Grade 3 Classic Kit"
                        });
                });

            modelBuilder.Entity("Himgiri.Core.Entities.SchoolKitItem", b =>
                {
                    b.Property<Guid>("SchoolKitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("SchoolKitId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("SchoolKitItems");

                    b.HasData(
                        new
                        {
                            SchoolKitId = new Guid("00000000-0000-0000-0007-000000000001"),
                            ItemId = new Guid("00000000-0000-0000-0004-000000000011"),
                            Quantity = 1
                        },
                        new
                        {
                            SchoolKitId = new Guid("00000000-0000-0000-0007-000000000001"),
                            ItemId = new Guid("00000000-0000-0000-0004-000000000012"),
                            Quantity = 3
                        },
                        new
                        {
                            SchoolKitId = new Guid("00000000-0000-0000-0007-000000000001"),
                            ItemId = new Guid("00000000-0000-0000-0004-000000000013"),
                            Quantity = 1
                        },
                        new
                        {
                            SchoolKitId = new Guid("00000000-0000-0000-0007-000000000002"),
                            ItemId = new Guid("00000000-0000-0000-0004-000000000001"),
                            Quantity = 1
                        },
                        new
                        {
                            SchoolKitId = new Guid("00000000-0000-0000-0007-000000000002"),
                            ItemId = new Guid("00000000-0000-0000-0004-000000000002"),
                            Quantity = 2
                        },
                        new
                        {
                            SchoolKitId = new Guid("00000000-0000-0000-0007-000000000002"),
                            ItemId = new Guid("00000000-0000-0000-0004-000000000003"),
                            Quantity = 1
                        },
                        new
                        {
                            SchoolKitId = new Guid("00000000-0000-0000-0007-000000000002"),
                            ItemId = new Guid("00000000-0000-0000-0004-000000000004"),
                            Quantity = 1
                        },
                        new
                        {
                            SchoolKitId = new Guid("00000000-0000-0000-0007-000000000002"),
                            ItemId = new Guid("00000000-0000-0000-0004-000000000005"),
                            Quantity = 1
                        },
                        new
                        {
                            SchoolKitId = new Guid("00000000-0000-0000-0007-000000000003"),
                            ItemId = new Guid("00000000-0000-0000-0004-000000000031"),
                            Quantity = 1
                        },
                        new
                        {
                            SchoolKitId = new Guid("00000000-0000-0000-0007-000000000003"),
                            ItemId = new Guid("00000000-0000-0000-0004-000000000032"),
                            Quantity = 1
                        },
                        new
                        {
                            SchoolKitId = new Guid("00000000-0000-0000-0007-000000000003"),
                            ItemId = new Guid("00000000-0000-0000-0004-000000000033"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Himgiri.Core.Entities.StockLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("NewQty")
                        .HasColumnType("integer");

                    b.Property<int>("OldQty")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("StockLogs");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("GstNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.VendorSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Gstin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvoicePrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LastInvoiceNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VendorSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Address = "Hinjawadi, Pune, Maharashtra",
                            CompanyName = "Himgiri Goods Pvt. Ltd",
                            ContactEmail = "support@himgirigoods.com",
                            ContactPhone = "PENDING_FROM_CLIENT",
                            CreatedAt = new DateTime(2026, 7, 1, 18, 45, 40, 233, DateTimeKind.Utc).AddTicks(4746),
                            Gstin = "PENDING_FROM_CLIENT",
                            InvoicePrefix = "HG",
                            IsActive = true,
                            IsDeleted = false,
                            LastInvoiceNumber = 0
                        });
                });

            modelBuilder.Entity("Himgiri.Infrastructure.Data.Models.SpGetCategoriesPagedResult", b =>
                {
                    b.Property<decimal>("CgstPercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("GstPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("HsnCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SgstPercent")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Himgiri.Infrastructure.Data.Models.SpGetGradesPagedResult", b =>
                {
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Himgiri.Infrastructure.Data.Models.SpGetItemsPagedResult", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GradeIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GradeNames")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStockInitialized")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Mrp")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("StockQty")
                        .HasColumnType("integer");

                    b.Property<int>("StorageStatus")
                        .HasColumnType("integer");

                    b.Property<int>("TargetQty")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Himgiri.Core.Entities.Item", b =>
                {
                    b.HasOne("Himgiri.Core.Entities.ItemCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Himgiri.Core.Entities.GstRate", "GstRate")
                        .WithMany()
                        .HasForeignKey("GstRateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("GstRate");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.ItemCategory", b =>
                {
                    b.HasOne("Himgiri.Core.Entities.GstRate", "DefaultGstRate")
                        .WithMany()
                        .HasForeignKey("DefaultGstRateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DefaultGstRate");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.ItemGrade", b =>
                {
                    b.HasOne("Himgiri.Core.Entities.Grade", "Grade")
                        .WithMany("ItemGrades")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Himgiri.Core.Entities.Item", "Item")
                        .WithMany("ItemGrades")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.Order", b =>
                {
                    b.HasOne("Himgiri.Core.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("Himgiri.Core.Entities.Item", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Himgiri.Core.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.OrderStatusHistory", b =>
                {
                    b.HasOne("Himgiri.Core.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.PriceAuditLog", b =>
                {
                    b.HasOne("Himgiri.Core.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("Himgiri.Core.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.PurchaseOrderItem", b =>
                {
                    b.HasOne("Himgiri.Core.Entities.Item", "Item")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Himgiri.Core.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.SchoolKit", b =>
                {
                    b.HasOne("Himgiri.Core.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.SchoolKitItem", b =>
                {
                    b.HasOne("Himgiri.Core.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Himgiri.Core.Entities.SchoolKit", "SchoolKit")
                        .WithMany("KitItems")
                        .HasForeignKey("SchoolKitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("SchoolKit");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.StockLog", b =>
                {
                    b.HasOne("Himgiri.Core.Entities.Item", "Item")
                        .WithMany("StockLogs")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.Grade", b =>
                {
                    b.Navigation("ItemGrades");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.Item", b =>
                {
                    b.Navigation("ItemGrades");

                    b.Navigation("OrderItems");

                    b.Navigation("PurchaseOrderItems");

                    b.Navigation("StockLogs");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.ItemCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.SchoolKit", b =>
                {
                    b.Navigation("KitItems");
                });

            modelBuilder.Entity("Himgiri.Core.Entities.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
